name: beyond-deduction
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aom=3.12.1=ha237518_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py313h03d0aa3_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.11.12=py313hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313h20e30b6_0
  - cpython=3.13.9=py313hd8ed1ab_101
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - filelock=3.20.0=py313hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py313h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.10.0=py313h7eb115d_0
  - gettext=0.21.0=hbdbcc25_2
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py313h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.7.0=py313hca03da5_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py313hca03da5_0
  - joblib=1.5.2=py313hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.9=py313haeee614_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libsodium=1.0.20=h99b78c6_0
  - libtiff=4.7.1=h367c460_0
  - libtorch=2.7.0=gpu_mps_hda230bc_200
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib=3.10.6=py313hca03da5_1
  - matplotlib-base=3.10.6=py313haa222d5_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py313hca03da5_0
  - nomkl=3.0=0
  - numexpr=2.14.1=py313h5fbe615_0
  - numpy=2.3.5=py313h4bb6f22_0
  - numpy-base=2.3.5=py313h23175f9_0
  - openssl=3.6.0=h5503f6c_0
  - opentelemetry-api=1.38.0=py313hca03da5_0
  - packaging=25.0=py313hca03da5_1
  - pandas=2.3.3=py313h3f644e9_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py313he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py313h9734d34_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py313hca03da5_0
  - python=3.13.9=hc7d8306_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-gil=3.13.9=h4df99d1_101
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=2_cp313
  - pytorch=2.7.0=gpu_mps_py313h91d4186_200
  - pytz=2025.2=py313hca03da5_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - readline=8.3=h0b18652_0
  - scikit-learn=1.7.2=py313h6316d20_0
  - scipy=1.16.3=py313h08a1045_0
  - seaborn=0.13.2=py313hca03da5_3
  - setuptools=80.9.0=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py313hca03da5_0
  - threadpoolctl=3.5.0=py313h7eb115d_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py313h80987f9_0
  - tqdm=4.67.1=py313h7eb115d_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py313hca03da5_0
  - typing_extensions=4.15.0=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=py313hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - charset-normalizer==3.4.4
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - tokenizers==0.22.1
      - transformers==4.57.3
      - urllib3==2.5.0
prefix: /opt/homebrew/anaconda3/envs/beyond-deduction
